exec-once=$HOME/.config/mango/autostart.sh
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=xrdb -merge ~/.Xresources
exec-once=gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once=gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once=kanshi
exec-once=waybar
exec-once=mako
exec-once=swayidle -w -C $HOME/.config/swayidle/config
exec-once=awww-daemon
exec-once=awww img ~/.config/ThemeSwitcher/wallpaper
exec-once=swayosd-server --config $HOME/.config/swayosd/config.toml -s $HOME/.config/swayosd/style.css
