# Basic window rules
windowrule=unfocused_opacity:0.85,focused_opacity:0.95,appid:kitty
windowrule=unfocused_opacity:0.55,focused_opacity:0.95,appid:foot
windowrule=unfocused_opacity:1.0,focused_opacity:1.0,appid:helium

windowrule=isfloating:1,title:Tekktonic,width:1600,height:900,isoverlay:1

windowrule=isfloating:1,title:1280x900,width:1280,height:900,isoverlay:1
windowrule=isfloating:1,title:2160x1080,width:2160,height:1080,isoverlay:1
windowrule=isfloating:1,title:800x600,width:800,height:600,isoverlay:1
