# Theme colors
rootcolor=0x19E4AFff
bordercolor=0x727169FF
focuscolor=0x19E4AFff
maximizescreencolor=0x19E4AFff
urgentcolor=0x19E4AFff
scratchpadcolor=0x19E4AFff
globalcolor=0x19E4AFff
overlaycolor=0x19E4AFff

# Shadows
shadowscolor=0x0A0A0Aff

# Mouse
env=XCURSOR_SIZE,24
# env=XCURSOR_THEME,Bibata-Modern-Ice
# cursor_theme=Bibata-Modern-Ice
# exec-once=gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'

# Other
env=GTK_THEME,Adwaita:dark
env=QT_STYLE_OVERRIDE,adwaita-dark
exec-once=gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once=gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
