[preferred]
default=gtk
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Inhibit=gtk

[org.keepassxc.KeePassXC]
org.freedesktop.impl.portal.FileChooser=gtk
