SECONDARY_COLOR = "cc99cc"
PRIMARY_COLOR = "66cccc"
TERTIARY_COLOR = "99cc99"
PRIMARY_TEXT_COLOR = "FFFFFF"
SECONDARY_TEXT_COLOR = "2d2d2d"
BACKGROUND = "2d2d2d"
FOREGROUND = "cccccc"

COLOR0 = "2d2d2d"
COLOR1 = "f2777a"
COLOR2 = "99cc99"
COLOR3 = "ffcc66"
COLOR4 = "6699cc"
COLOR5 = "cc99cc"
COLOR6 = "66cccc"
COLOR7 = "cccccc"

# BRIGHT VARIANTS
COLOR8 = "999999"
COLOR9 = "f2777a"
COLOR10 = "99cc99"
COLOR11 = "ffcc66"
COLOR12 = "6699cc"
COLOR13 = "cc99cc"
COLOR14 = "66cccc"
COLOR15 = "ffffff"

SELECTION_BG = "515151"
SELECTION_FG = "cccccc"
URLS = "66cccc"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Blue"

WALLPAPER = "/Download/12423273.jpg"
TAGS         = []
