PRIMARY_COLOR = "3584E4"
SECONDARY_COLOR = "FFA348"
TERTIARY_COLOR = "A11299"
PRIMARY_TEXT_COLOR = "cdcecf"
SECONDARY_TEXT_COLOR = "192330"
BACKGROUND = "192330"
FOREGROUND = "cdcecf"

COLOR0 = "393b44"
COLOR1 = "c94f6d"
COLOR2 = "81b29a"
COLOR3 = "dbc074"
COLOR4 = "719cd6"
COLOR5 = "9d79d6"
COLOR6 = "63cdcf"
COLOR7 = "dfdfe0"

# BRIGHT VARIANTS
COLOR8 = "738091"
COLOR9 = "c94f6d"
COLOR10 = "81b29a"
COLOR11 = "dbc074"
COLOR12 = "719cd6"
COLOR13 = "9d79d6"
COLOR14 = "63cdcf"
COLOR15 = "d6d6d7"

SELECTION_BG = "2b3b51"
SELECTION_FG = "cdcecf"
URLS = "63cdcf"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "oreo_blue_cursors"

WALLPAPER = "/Tekk/butterflies.png"
