PRIMARY_COLOR = "00f0ff"
SECONDARY_COLOR = "C061CB"
TERTIARY_COLOR = "8FF0A4"
PRIMARY_TEXT_COLOR = "e0e6ed"
SECONDARY_TEXT_COLOR = "0b0e14"
BACKGROUND = "0b0e04"
FOREGROUND = "00f0ff"

COLOR0 = "0b0e14"
COLOR1 = "d32f2f"
COLOR2 = "00c853"
COLOR3 = "ffab00"
COLOR4 = "0079FF"
COLOR5 = "BC13FE"
COLOR6 = "00B8D4"
COLOR7 = "A9B1D6"

# BRIGHT VARIANTS
COLOR8 = "454B59"
COLOR9 = "FF5252"
COLOR10 = "69F0AE"
COLOR11 = "FFD740"
COLOR12 = "008AFF"
COLOR13 = "E040FB"
COLOR14 = "00F0FF"
COLOR15 = "FFFFFF"

SELECTION_BG = "3e206d"
SELECTION_FG = "ffffff"
URLS = "00aaff"
SHADOW_COLOR = "020204"

MOUSE_THEME = "Drop-Purple"

WALLPAPER = "/Cars/Car-14.jpeg"
TAGS         = []
