NAME                 = "car11"

PRIMARY_COLOR        = "356175"
SECONDARY_COLOR      = "752522"
TERTIARY_COLOR       = "D83616"
PRIMARY_TEXT_COLOR   = "C8B3A5"
SECONDARY_TEXT_COLOR = "FFFFFF"
BACKGROUND           = "000000"
FOREGROUND           = "C8B3A5"

COLOR0  = "1A1A1A"
COLOR1  = "CD0000"
COLOR2  = "00CD00"
COLOR3  = "CDCD00"
COLOR4  = "2F3D9F"
COLOR5  = "CD00CD"
COLOR6  = "00CDCD"
COLOR7  = "E5E5E5"
COLOR8  = "535353"
COLOR9  = "DA4040"
COLOR10 = "40DA40"
COLOR11 = "DADA40"
COLOR12 = "4040F2"
COLOR13 = "DA40DA"
COLOR14 = "40DADA"
COLOR15 = "ECECEC"

SELECTION_BG = "44475A"
SELECTION_FG = "EFEFEF"
URLS         = "5C5CFF"
SHADOW_COLOR = "4E0909"

MOUSE_THEME  = "default"
WALLPAPER    = "/Cars/Car-11.jpg"
TAGS         = []
