PRIMARY_COLOR = "8959a8"
SECONDARY_COLOR = "f5871f"
TERTIARY_COLOR = "3e999f"
PRIMARY_TEXT_COLOR = "ffffff"
SECONDARY_TEXT_COLOR = "000000"
BACKGROUND = "1d1f21"
FOREGROUND = "eeeeee"

COLOR0 = "ffffff"
COLOR1 = "c82829"
COLOR2 = "718c00"
COLOR3 = "eab700"
COLOR4 = "4271ae"
COLOR5 = "8959a8"
COLOR6 = "3e999f"
COLOR7 = "4d4d4c"

# BRIGHT VARIANTS
COLOR8 = "8e908c"
COLOR9 = "c82829"
COLOR10 = "718c00"
COLOR11 = "eab700"
COLOR12 = "4271ae"
COLOR13 = "8959a8"
COLOR14 = "3e999f"
COLOR15 = "1d1f21"

SELECTION_BG = "d6d6d6"
SELECTION_FG = "000000"
URLS = "3e999f"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Blue"

WALLPAPER = "/Chimera/chimera1.jpeg"
