PRIMARY_COLOR = "d8a657"
SECONDARY_COLOR = "95c4b8"
TERTIARY_COLOR = "b8c675"
PRIMARY_TEXT_COLOR = "eaddc5"
SECONDARY_TEXT_COLOR = "3c3836"
BACKGROUND = "282828"
FOREGROUND = "f4fef8"

COLOR0 = "3c3836"
COLOR1 = "ea6962"
COLOR2 = "a9b665"
COLOR3 = "d8a657"
COLOR4 = "7daea3"
COLOR5 = "d3869b"
COLOR6 = "89b482"
COLOR7 = "d4be98"

# BRIGHT VARIANTS
COLOR8 = "928374"
COLOR9 = "f7887f"
COLOR10 = "b8c675"
COLOR11 = "e6b566"
COLOR12 = "95c4b8"
COLOR13 = "e89eb6"
COLOR14 = "a2cd9b"
COLOR15 = "eaddc5"

SELECTION_BG = "3c3836"
SELECTION_FG = "d4be98"
URLS = "89b482"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "oreo_spark_orange_cursors"

WALLPAPER = "/Chimera/chimera8.jpeg"
