PRIMARY_COLOR = "7daea3"
SECONDARY_COLOR = "89b482"
TERTIARY_COLOR = "d8a657"
PRIMARY_TEXT_COLOR = "282828"
BACKGROUND = "282828"
FOREGROUND = "d4be98"

COLOR0 = "3c3836"
COLOR1 = "ea6962"
COLOR2 = "a9b665"
COLOR3 = "d8a657"
COLOR4 = "7daea3"
COLOR5 = "d3869b"
COLOR6 = "89b482"
COLOR7 = "d4be98"

# BRIGHT VARIANTS
COLOR8 = "3c3836"
COLOR9 = "ea6962"
COLOR10 = "a9b665"
COLOR11 = "d8a657"
COLOR12 = "7daea3"
COLOR13 = "d3869b"
COLOR14 = "89b482"
COLOR15 = "d4be98"

SELECTION_BG = "3c3836"
SELECTION_FG = "d4be98"
URLS = "89b482"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "oreo_teal_cursors"

WALLPAPER = "/Self/dendritic.jpeg"
