NAME                 = "fedora7"

PRIMARY_COLOR        = "1D1D1D"
SECONDARY_COLOR      = "1D1D1D"
TERTIARY_COLOR       = "1D1D1D"
PRIMARY_TEXT_COLOR   = "C2C2C2"
SECONDARY_TEXT_COLOR = "77767B"
BACKGROUND           = "050505"
FOREGROUND           = "C2C2C2"

COLOR0  = "1A1A1A"
COLOR1  = "CD0000"
COLOR2  = "00CD00"
COLOR3  = "CDCD00"
COLOR4  = "0000EE"
COLOR5  = "CD00CD"
COLOR6  = "00CDCD"
COLOR7  = "E5E5E5"
COLOR8  = "7F7F7F"
COLOR9  = "FF0000"
COLOR10 = "00FF00"
COLOR11 = "FFFF00"
COLOR12 = "5C5CFF"
COLOR13 = "FF00FF"
COLOR14 = "00FFFF"
COLOR15 = "FFFFFF"

SELECTION_BG = "44475A"
SELECTION_FG = "EFEFEF"
URLS         = "5C5CFF"
SHADOW_COLOR = "000000"

MOUSE_THEME  = "default"
WALLPAPER    = "/Fedora/fedora-07.jpg"
TAGS         = []
