PRIMARY_COLOR = "8aadf4"
SECONDARY_COLOR = "8bd5ca"
TERTIARY_COLOR = "D8A657"
PRIMARY_TEXT_COLOR = "24273a"
SECONDARY_TEXT_COLOR = "24273a"
BACKGROUND = "24273a"
FOREGROUND = "cad3f5"

COLOR0 = "494d64"
COLOR1 = "ed8796"
COLOR2 = "a6da95"
COLOR3 = "eed49f"
COLOR4 = "8aadf4"
COLOR5 = "f5bde6"
COLOR6 = "8bd5ca"
COLOR7 = "b8c0e0"

# BRIGHT VARIANTS
COLOR8 = "5b6078"
COLOR9 = "ed8796"
COLOR10 = "a6da95"
COLOR11 = "eed49f"
COLOR12 = "8aadf4"
COLOR13 = "f5bde6"
COLOR14 = "8bd5ca"
COLOR15 = "a5adcb"

SELECTION_BG = "f4dbd6"
SELECTION_FG = "24273a"
URLS = "8bd5ca"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "oreo_teal_cursors"

WALLPAPER = "/Ublue/huntress.png"
