PRIMARY_COLOR = "509475"
SECONDARY_COLOR = "2DD5B7"
TERTIARY_COLOR = "0F4804"
PRIMARY_TEXT_COLOR = "F6F6DD"
SECONDARY_TEXT_COLOR = "C8FD96"
BACKGROUND = "111c18"
FOREGROUND = "F6F5DD"

COLOR0 = "23372B"
COLOR1 = "05570F"
COLOR2 = "549e6a"
COLOR3 = "459451"
COLOR4 = "509475"
COLOR5 = "8FF0A4"
COLOR6 = "2DD5B7"
COLOR7 = "F6F5DD"

# BRIGHT VARIANTS
COLOR8 = "53685B"
COLOR9 = "05570F"
COLOR10 = "143614"
COLOR11 = "8FF0A4"
COLOR12 = "ACD4CF"
COLOR13 = "75bbb3"
COLOR14 = "8CD3CB"
COLOR15 = "9eebb3"

SELECTION_BG = "23372B"
SELECTION_FG = "F6F5DD"
URLS = "8CD3CB"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Alien"

WALLPAPER = "/Download/osaka-jade-3-osaka-jade-bg.jpg"
