PRIMARY_COLOR = "7e9cd8"
SECONDARY_COLOR = "6a9589"
TERTIARY_COLOR = "c0a36e"
PRIMARY_TEXT_COLOR = "dcd7ba"
SECONDARY_TEXT_COLOR = "1f1f28"
BACKGROUND = "1f1f28"
FOREGROUND = "dcd7ba"

COLOR0 = "090618"
COLOR1 = "c34043"
COLOR2 = "76946a"
COLOR3 = "c0a36e"
COLOR4 = "7e9cd8"
COLOR5 = "957fb8"
COLOR6 = "6a9589"
COLOR7 = "c8c093"

# BRIGHT VARIANTS
COLOR8 = "727169"
COLOR9 = "e82424"
COLOR10 = "98bb6c"
COLOR11 = "e6c384"
COLOR12 = "7fb4ca"
COLOR13 = "938aa9"
COLOR14 = "7aa89f"
COLOR15 = "dcd7ba"

SELECTION_BG = "2d4f67"
SELECTION_FG = "c8c093"
URLS = "7aa89f"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Purple"

WALLPAPER = "/Download/11083386.jpg"
