PRIMARY_COLOR = "C93209"
SECONDARY_COLOR = "F55D16"
TERTIARY_COLOR = "FF9136"
PRIMARY_TEXT_COLOR = "FFAAAA"
SECONDARY_TEXT_COLOR = "0A0200"
BACKGROUND = "0A0200"
FOREGROUND = "CFBCB6"

COLOR0 = "260C06"
COLOR1 = "C93209"
COLOR2 = "6B5C45"
COLOR3 = "D66C0F"
COLOR4 = "F04E23"
COLOR5 = "8F4D4D"
COLOR6 = "9C6B58"
COLOR7 = "CFBCB6"

# BRIGHT VARIANTS
COLOR8 = "452821"
COLOR9 = "FF5500"
COLOR10 = "9E8C6B"
COLOR11 = "FFB84C"
COLOR12 = "FF7043"
COLOR13 = "C93209"
COLOR14 = "D6967E"
COLOR15 = "FFFFFF"

SELECTION_BG = "C93209"
SELECTION_FG = "FFB84C"
URLS = "D66C0F"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Blood"

WALLPAPER = "/MesoAmerica/rage-lava.jpeg"
TAGS         = []
