PRIMARY_COLOR = "7aa6da"
SECONDARY_COLOR = "b9ca4a"
TERTIARY_COLOR = "e78c45"
PRIMARY_TEXT_COLOR = "eaeaea"
SECONDARY_TEXT_COLOR = "000000"
BACKGROUND = "000000"
FOREGROUND = "eaeaea"

COLOR0 = "000000"
COLOR1 = "d54e53"
COLOR2 = "b9ca4a"
COLOR3 = "e7c547"
COLOR4 = "7aa6da"
COLOR5 = "c397d8"
COLOR6 = "70c0b1"
COLOR7 = "eaeaea"

# BRIGHT VARIANTS
COLOR8 = "969896"
COLOR9 = "d54e53"
COLOR10 = "b9ca4a"
COLOR11 = "e7c547"
COLOR12 = "7aa6da"
COLOR13 = "c397d8"
COLOR14 = "70c0b1"
COLOR15 = "ffffff"

SELECTION_BG = "424242"
SELECTION_FG = "eaeaea"
URLS = "70c0b1"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Blue"

WALLPAPER = "/Self/lone-castle.jpeg"
