PRIMARY_COLOR = "b294bb"
SECONDARY_COLOR = "b294bb"
TERTIARY_COLOR = "de935f"
PRIMARY_TEXT_COLOR = "c5c8c6"
SECONDARY_TEXT_COLOR = "1d1f21"
BACKGROUND = "1d1f21"
FOREGROUND = "c5c8c6"

COLOR0 = "1d1f21"
COLOR1 = "cc6666"
COLOR2 = "b5bd68"
COLOR3 = "f0c674"
COLOR4 = "81a2be"
COLOR5 = "b294bb"
COLOR6 = "8abeb7"
COLOR7 = "c5c8c6"

# BRIGHT VARIANTS
COLOR8 = "969896"
COLOR9 = "cc6666"
COLOR10 = "b5bd68"
COLOR11 = "f0c674"
COLOR12 = "81a2be"
COLOR13 = "b294bb"
COLOR14 = "8abeb7"
COLOR15 = "ffffff"

SELECTION_BG = "373b41"
SELECTION_FG = "0A0A0A"
URLS = "8abeb7"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Blue"

WALLPAPER = "/Download/demon.png"
