PRIMARY_COLOR = "00FFEA"
SECONDARY_COLOR = "BD00FF"
TERTIARY_COLOR = "00FF66"
PRIMARY_TEXT_COLOR = "E6EDF3"
SECONDARY_TEXT_COLOR = "050508"
BACKGROUND = "050508"
FOREGROUND = "E6EDF3"

COLOR0 = "050508"
COLOR1 = "FF0055"
COLOR2 = "00FF66"
COLOR3 = "FFEA00"
COLOR4 = "2D72FF"
COLOR5 = "BD00FF"
COLOR6 = "00FFEA"
COLOR7 = "D0D0D0"

# BRIGHT VARIANTS
COLOR8 = "303030"
COLOR9 = "FF4D88"
COLOR10 = "5CFF9E"
COLOR11 = "FFF266"
COLOR12 = "6699FF"
COLOR13 = "D54DFF"
COLOR14 = "80FFF5"
COLOR15 = "FFFFFF"

SELECTION_BG = "D300C4"
SELECTION_FG = "FFFFFF"
URLS = "2D72FF"
SHADOW_COLOR = "000000"

MOUSE_THEME = "Drop-Blue"
WALLPAPER = "/Void/void-colorful.jpeg"
