PRIMARY_COLOR = "478061"
SECONDARY_COLOR = "7b7b7b"
TERTIARY_COLOR = "afafaf"
PRIMARY_TEXT_COLOR = "F8F8FD"
SECONDARY_TEXT_COLOR = "0A0A0F"
BACKGROUND = "0A0A0F"
FOREGROUND = "E8F7FD"


COLOR0 = "000000"
COLOR1 = "CCCC66"
COLOR2 = "00FF99"
COLOR3 = "DDDD88"
COLOR4 = "00CC77"
COLOR5 = "66FF66"
COLOR6 = "00FFCC"
COLOR7 = "AAFFCC"

# BRIGHT VARIANTS 
COLOR8 = "333333"
COLOR9 = "EEEEAA"
COLOR10 = "00FF99"
COLOR11 = "FFFFDD"
COLOR12 = "33FF99"
COLOR13 = "99FF99"
COLOR14 = "00FFCC"
COLOR15 = "CCFFEE"

SELECTION_BG = "478061"
SELECTION_FG = "F8F8FD"
URLS = "7BA7D1"
SHADOW_COLOR = "0A0A0A"

MOUSE_THEME = "Drop-Alien"

WALLPAPER = "/Void/void_logo_v7.jpeg"
