
# BLACK
color0                              #2d2d2d
color8                              #999999

# RED 
color1                              #f2777a
color9                              #f2777a

# GREEN
color2                              #99cc99
color10                             #99cc99

# YELLOW
color3                              #ffcc66
color11                             #ffcc66

# BLUE
color4                              #6699cc
color12                             #6699cc

# MAGENTA
color5                              #cc99cc
color13                             #cc99cc

# CYAN
color6                              #66cccc
color14                             #66cccc

# WHITE
color7                              #cccccc
color15                             #ffffff

foreground                          #cccccc
background                          #2d2d2d
selection_foreground                #cccccc
selection_background                #515151

active_tab_foreground               #66cccc
active_tab_background               #2d2d2d
inactive_tab_foreground             #cc99cc
inactive_tab_background             #2d2d2d

cursor                              #cc99cc
cursor_text_color                   #cccccc
cursor_trail_color                  #66cccc

url_color                           #66cccc
mark1_foreground                    black
mark1_background                    #66cccc
mark2_foreground                    black
mark2_background                    #cc99cc
mark3_foreground                    black
mark3_background                    #99cc99

background_opacity                  0.8
background_blur                     1
transparent_background_colors       red@0.5 #00ff00@0.3
dynamic_background_opacity          no
dim_opacity                         0.4

wayland_titlebar_color              background
