# Theme colors
rootcolor=0x66ccccff
bordercolor=0xcc99ccFF
focuscolor=0x66ccccff
maximizescreencolor=0x66ccccff
urgentcolor=0x66ccccff
scratchpadcolor=0x66ccccff
globalcolor=0x66ccccff
overlaycolor=0x66ccccff

# Shadows
shadowscolor=0x0A0A0Aff

# Mouse
env=XCURSOR_SIZE,24
env=XCURSOR_THEME,Drop-Blue
cursor_theme=Drop-Blue
exec-once=gsettings set org.gnome.desktop.interface cursor-theme 'Drop-Blue'

# Other
env=GTK_THEME,Adwaita:dark
env=QT_STYLE_OVERRIDE,adwaita-dark
exec-once=gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once=gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
