# Misc
bind=SUPER,slash,spawn,bitwarden

# Native apps (SUPER+SHIFT)
bind=SUPER+SHIFT,b,spawn,kitty --title 1280x900 btop
bind=SUPER+SHIFT,f,spawn,kitty --title 1280x900 spf
bind=SUPER+SHIFT,h,spawn,kitty --title 800x600 htop -C
bind=SUPER+SHIFT,i,spawn,kitty --title 800x600 impala
bind=SUPER+SHIFT,l,spawn,kitty --title 800x600 lazygit
bind=SUPER+SHIFT,m,spawn,spotify-launcher
bind=SUPER+SHIFT,n,spawn,kitty --title 1280x900 nvim
bind=SUPER+SHIFT,t,spawn,helium
bind=SUPER+SHIFT,u,spawn,kitty --title 800x600 bluetui
bind=SUPER+SHIFT,y,spawn,kitty --title 1280x900 yazi

# Webapp shortcuts (SUPER+ALT)
bind=SUPER+ALT,a,spawn,helium --app=https://www.audible.com
bind=SUPER+ALT,d,spawn,helium --app=https://discord.com
bind=SUPER+ALT,g,spawn,helium --app=https://gemini.google.com/gem/a2e9c5b0e7e1
bind=SUPER+ALT,n,spawn,helium --app=https://netflix.com
bind=SUPER+ALT,u,spawn,helium --app=https://upwork.com
bind=SUPER+ALT,y,spawn,helium --app=https://youtube.com
bind=CTRL+SHIFT,space,spawn,helium --app=https://www.nerdfonts.com/cheat-sheet
