mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=SUPER,btn_middle,togglefloating

gesturebind=none,left,3,focusdir,left
gesturebind=none,right,3,focusdir,right
gesturebind=none,up,3,focusdir,up
gesturebind=none,down,3,focusdir,down
gesturebind=none,left,4,viewtoleft_have_client,0
gesturebind=none,right,4,viewtoright_have_client,0
gesturebind=none,up,4,toggleoverview
gesturebind=none,down,4,toggleoverview

bind=NONE,XF86AudioRaiseVolume,spawn, swayosd-client --output-volume +2
bind=NONE,XF86AudioLowerVolume,spawn, swayosd-client --output-volume -2
bind=NONE,XF86AudioMute,spawn, swayosd-client --output-volume mute-tog

bind=NONE,XF86AudioPlay,spawn, swayosd-client --playerctl play-pause 
bind=NONE,XF86AudioStop,spawn, swayosd-client --playerctl stop
bind=NONE,XF86AudioNext,spawn, swayosd-client --playerctl next 
bind=NONE,XF86AudioPrev,spawn, swayosd-client --playerctl prev 

bind=NONE,XF86MonBrightnessUp,spawn,swayosd-client --brightness +2
bind=NONE,XF86MonBrightnessDown,spawn,swayosd-client --brightness -2
