# monitor focus
bind=super+ctrl,left,focusmon,left
bind=super+ctrl,right,focusmon,right
bind=super+ctrl,up,focusmon,up
bind=super+ctrl,down,focusmon,down

# move to monitor
bind=super+alt+shift,left,tagmon,left
bind=super+alt+shift,right,tagmon,right
bind=super+alt+shift,up,tagmon,up
bind=super+alt+shift,down,tagmon,down
