# Wofi launchers and menus
bind=SUPER,space,spawn,wofi --show drun
bind=SUPER,v,spawn,~/.local/bin/wofi-clipboard-menu

# Dim lights
bind=SUPER+CTRL,l,spawn,~/.local/bin/toggle-sunset

# Lock screen
bind=SUPER+CTRL,Escape,spawn,swaylock -F -f -C ~/.config/swaylock/config

# Notification center
bind=SUPER,backspace,spawn, makoctl restore
bind=SUPER+SHIFT,backspace,spawn, makoctl dismiss --all

# Waybar
bind=SUPER+ALT,b,spawn_shell,~/.local/bin/tekktrestart-waybar

# Wallpaper switcher
bind=SUPER+CTRL,w,spawn_shell,tekktonic-gui

# Power menu
bind=SUPER,Escape,spawn,wlogout -sC ~/.config/wlogout/style.css -l ~/.config/wlogout/layout

# Scratchpad
bind=SUPER,minus,toggle_scratchpad

# Screenshots
bind=None,Print,spawn,grim ~/Pictures/screenshot-$(date +%Y%m%d-%H%M%S).png
bind=CTRL+ALT,4,spawn,grim - | wl-copy
bind=CTRL+SHIFT,4,spawn,~/.local/bin/screenshot-area --clipboard
bind=CTRL+ALT,a,spawn_shell,grim -g "$(slurp -b '#2E2A1E55' -c '#88c0d0ff')" -t ppm - | satty -f -
